### PR TITLE
new

### PR DESCRIPTION
**Pull request by aydar013**

### CODE REVIEW

**Comment by FiLLa-FaS** [comment]
Hi! Thanks for sending your project for review - it already looks good! I especially likt your jsx markup and that both pages look similar to the mockup on desktop screen resolutions. I left several small comments below and hope that you can deal with them easily. Good luck!✨

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
    * Mismatches for home page on 768 viewport https://pasteboard.co/B0sPfeqj9F0w.png https://pasteboard.co/Dx1qy4lBwsDj.png
    * Mismatches for home page on 320 viewport https://pasteboard.co/GMVAYjpMYXmT.png
    * Mismatches for saved-news page on 768 viewport https://pasteboard.co/ZSxtmnrtnbEh.png 
    * Mismatches for saved-news page on 320 viewport https://pasteboard.co/iwoRVMm8gog3.png
- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * All pages content should be centered horizontally on intermediate screen resolutions
    * The home page scrolls horizontally on 450px - 710px, 801px - 1204px screen resolutions
- [ ]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
    * Tripleten link in footer section should open in a new tab
- [ ]  Classes are named according to BEM specifications.
    * All BEM elements should be placed inside their block, you can't use element outside its block. For example, `navbar__logo` class is placed outside the `navbar` block. You should check and fix **all similar cases throughout the project**
    * The item can't be a block and the element of the same block at one time. For example, there's a tag with `error-message error-message__signin-email` classes.  You should check and fix **all similar cases throughout the project**
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [ ]  There are no linting errors or warnings.
    * The project has several eslint warnings

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
    * search-form button and "show more" button don't have hover states (and search-form button should also have active state)
- [ ]  The design reuses components wherever possible.
    * You can reuse header, menu, navbar and news cards instead of creating two versions of each component - for home page and for saved-news page
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [ ]  Form elements should be highlighted when focused.
    * `switch__login-signup` should be highlighted when focused
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 47

**Comment by FiLLa-FaS** [comment]
Hi! Thanks for the corrections, your project looks much better! I left several comments below, please fix them to improve your project and get more points. Good luck!✨

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
    * There shouldn't be a burger icon before the `home` tab on `saved-articles` page on tablet and desktop screen resolutions
    * Mismatches for saved-news page on 320 viewport https://pasteboard.co/mLubHZLLP42L.png
- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * `search-form` should be centered horizontally between 320px and 450px screen resolutions
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.
    * All BEM elements should be placed inside their block, you can't use element outside its block. For example, `navbar__logo` class is placed outside the `navbar` block https://pasteboard.co/vefClQtnIULb.png. You should check and fix all similar cases throughout the project
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [ ]  There are no linting errors or warnings.
    * The project has several eslint warnings https://pasteboard.co/FvDlPGi42y39.png

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [ ]  The design reuses components wherever possible.
    * You can reuse header, menu, navbar and news cards instead of creating two versions of each component - for home page and for saved-news page
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 64

**Comment by FiLLa-FaS** [comment]
Hi! I see that you've made some changes, but unfortunately the points are the same this time, you need to fix some more issues and make sure that these issues are fixed throughout the page. Good luck!

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
    * Mismatches for saved-news page on 320 viewport https://pasteboard.co/mLubHZLLP42L.png
- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * The home page scrolls horizontally on 450px - 710px, 801px - 1203px screen resolutions
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.
    * All BEM elements should be placed inside their block, you can't use element outside its block. For example, `navbar__logo` class is placed outside the `navbar` block https://pasteboard.co/vefClQtnIULb.png. You should check and fix all similar cases throughout the project
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [ ]  There are no linting errors or warnings.
    * The project has several eslint warnings https://pasteboard.co/FvDlPGi42y39.png

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [ ]  The design reuses components wherever possible.
    * You can reuse header, menu, navbar and news cards instead of creating two versions of each component - for home page and for saved-news page
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 64

**Comment by aydar013** [comment]
Hello, but i fixed those problems. For example this:
https://github.com/aydar013/news-explorer-frontend/assets/121465617/ef837bd9-0089-4566-8063-7d49d16d9087
and no eslint warnings anymore:
https://github.com/aydar013/news-explorer-frontend/assets/121465617/ce64b53a-186b-46d5-a38e-093095fac1c1
And others. I recommited again right now, maybe it'll help

**Comment by FiLLa-FaS** [comment]
Hi! Yep, this time I see all changes - you've done an amazing job - I'm happy to accept your project. But you still can work on your BEM implementation if you want. Good luck on the next stage!

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
- [x]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.
    * All BEM elements should be placed inside their block, you can't use element outside its block. For example, `navbar__home` class is placed outside the `navbar` block https://pasteboard.co/SGcaJdDkEoUq.png. **You should check and fix all similar cases throughout the project**
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 96

**Pull request merged**
